version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "LINEbotFitness"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1lsd1f1o23h47"
s3_prefix = "LINEbotFitness"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
